### ISSUE TITLE
LinAlgError: Singular matrix error

### ISSUE THREAD

**Issue by Freddsle** [mahdiiix/fedcombat#2]
https://github.com/mahdiiix/fedcombat/blob/bea2e15da6383d5ce1098fc83b4fb44afdbf6cff/states.py#L138

When replaced all values in batch column in the design file to zeros - got new error "numpy.linalg.LinAlgError: Singular matrix"
```

					2024-08-30 12:19:26,679 CRIT Supervisor is running as root.  Privileges were not dropped because no user is specified in the config file.  If you intend to run as root, you can set user=root in the config file to avoid this message.
2024-08-30 12:19:26,681 INFO supervisord started with pid 7
2024-08-30 12:19:27,688 INFO spawned: 'app' with pid 8
2024-08-30 12:19:27,691 INFO spawned: 'nginx' with pid 9
Bottle v0.12.25 server starting up (using WSGIRefServer())...
Listening on http://localhost:5000/
Hit Ctrl-C to quit.

2024-08-30 12:19:29,276 INFO success: app entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
2024-08-30 12:19:29,276 INFO success: nginx entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
[CTRL] POST /setup
[Time: 30.08.24 12:19:41] [Level: info] id: 560ac7da9fd69cc1
[Time: 30.08.24 12:19:41] [Level: info] coordinator: True
[Time: 30.08.24 12:19:41] [Level: info] clients: ['23992b059d977ea8', '560ac7da9fd69cc1', 'd2625bc6e2cd28d5']
[Time: 30.08.24 12:19:41] [Level: info] state: initial
127.0.0.1 - - [30/Aug/2024 12:19:41] "POST /api/setup HTTP/1.0" 200 0
127.0.0.1 - - [30/Aug/2024 12:19:41] "GET /api/status HTTP/1.0" 200 155
[Time: 30.08.24 12:19:41] [Level: info] transition: precalculation
[Time: 30.08.24 12:19:42] [Level: info] state: precalculation
127.0.0.1 - - [30/Aug/2024 12:19:43] "GET /api/status HTTP/1.0" 200 162
[CTRL] POST /data
127.0.0.1 - - [30/Aug/2024 12:19:43] "POST /api/data?client=d2625bc6e2cd28d5&memo=GATHERROUND1 HTTP/1.0" 200 0
127.0.0.1 - - [30/Aug/2024 12:19:45] "GET /api/status HTTP/1.0" 200 162
[CTRL] POST /data
127.0.0.1 - - [30/Aug/2024 12:19:45] "POST /api/data?client=23992b059d977ea8&memo=GATHERROUND1 HTTP/1.0" 200 0
[Time: 30.08.24 12:19:45] [Level: info] transition: genes_drop
127.0.0.1 - - [30/Aug/2024 12:19:45] "POST /api/data?client=d2625bc6e2cd28d5&memo=GATHERROUND2 HTTP/1.0" 200 0
[CTRL] POST /data
[Time: 30.08.24 12:19:46] [Level: info] state: genes_drop
[Time: 30.08.24 12:19:46] [Level: info] transition: genes_drop_union
127.0.0.1 - - [30/Aug/2024 12:19:47] "GET /api/status HTTP/1.0" 200 164
[CTRL] POST /data
127.0.0.1 - - [30/Aug/2024 12:19:47] "POST /api/data?client=23992b059d977ea8&memo=GATHERROUND2 HTTP/1.0" 200 0
[Time: 30.08.24 12:19:47] [Level: info] state: genes_drop_union
[Time: 30.08.24 12:19:47] [Level: info] transition: drop_genes
[Time: 30.08.24 12:19:48] [Level: info] state: drop_genes
[Time: 30.08.24 12:19:48] [Level: info] transition: ols
127.0.0.1 - - [30/Aug/2024 12:19:49] "GET /api/status HTTP/1.0" 200 165
[CTRL] GET /data
127.0.0.1 - - [30/Aug/2024 12:19:49] "GET /api/data HTTP/1.0" 200 81534
[Time: 30.08.24 12:19:49] [Level: info] state: ols
[Time: 30.08.24 12:19:49] [Level: info] transition: ols_agg
[Time: 30.08.24 12:19:50] [Level: info] state: ols_agg
127.0.0.1 - - [30/Aug/2024 12:19:51] "GET /api/status HTTP/1.0" 200 155
[CTRL] POST /data
127.0.0.1 - - [30/Aug/2024 12:19:51] "POST /api/data?client=23992b059d977ea8&memo=GATHERROUND3 HTTP/1.0" 200 0
[CTRL] POST /data
127.0.0.1 - - [30/Aug/2024 12:19:51] "POST /api/data?client=d2625bc6e2cd28d5&memo=GATHERROUND3 HTTP/1.0" 200 0
[Time: 30.08.24 12:19:51] [Level: info] Traceback (most recent call last):
  File "/root/.local/lib/python3.8/site-packages/FeatureCloud/app/engine/app.py", line 252, in guarded_run
    self.run()
  File "/root/.local/lib/python3.8/site-packages/FeatureCloud/app/engine/app.py", line 271, in run
    transition = self.current_state.run()
  File "/app/states.py", line 138, in run
    B_hat = np.linalg.solve(xtx, xty)
  File "<__array_function__ internals>", line 200, in solve
  File "/root/.local/lib/python3.8/site-packages/numpy/linalg/linalg.py", line 386, in solve
    r = gufunc(a, b, signature=signature, extobj=extobj)
  File "/root/.local/lib/python3.8/site-packages/numpy/linalg/linalg.py", line 89, in _raise_linalgerror_singular
    raise LinAlgError("Singular matrix")
numpy.linalg.LinAlgError: Singular matrix

127.0.0.1 - - [30/Aug/2024 12:19:53] "GET /api/status HTTP/1.0" 200 161
```
With this data:
[example_data.zip](https://github.com/user-attachments/files/16816991/example_data.zip)

**Comment by mahdiiix** [comment]
It says you xtx is not invertible . that's a problem of the dataset imo. maybe the rows are linearly related. I will check it

**Comment by Freddsle** [comment]
> that's a problem of the dataset imo.

Yes, you probably right. It was a problem with sample info.
If the numeration of batch column starts with 1, it also doesnt work. 

I fixed sample info and it worked.
